config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  devise_for :users
  resources :users, only: %i[index show] do
    resources :friendships, only: %i[create] do
      collection do
        get 'accept_friend'
        get 'decline_friend'
      end
    end
  end
  
  put '/users/:id', to:  'users#update_img'

  resources :posts, only: %i[index new create show destroy] do
      resources :likes, only: %i[create]
  end
  resources :comments, only: %i[new create destroy] do
    resources :likes, only: %i[create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @all_posts = current_user.friends_and_own_posts
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(posts_params)
      if @post.save
        flash[:notice]="Post created"
        redirect_to @post
      else
        flash[:alert]="Something went wron while creating post"
        render 'new'
      end
  end

  def destroy
    
  end

  private
  def posts_params
   params.require(:post).permit(:content, :imageURL)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post_layout.html.erb
<div class="col-md-7 mx-auto card-lg bg-light shadow">

  <div class="container">
    <div class="row mt-3">
      <div class="ml-2">
      <% if object.user.image_url %>
        <%= image_tag(object.user.image.url, class: "img-profile")%>
      <%end%>
      </div>
      <div class="mt-2">
        <div class="col font-weight-bold">
          <%= link_to user_path(object.user), class: "font-raleway" do%>
            <%= object.user.full_name %>
          <%end%>
        </div>
        <div class="col size-12">Posted <%= distance_of_time_in_words(object.created_at, Time.now) %> ago</div>
      </div>
    </div>
  </div>

  <div class="container-fluid mt-4 p-0">
      <div class="size-18 text-post">
        <%= object.content %>
      </div>

  
        <div class="size-18 text-post mb-2 ml-3">
          <%= object.content %>
        </div>
    <% if current_user.id == object.user_id%>
      <%= link_to post_path(object), method: :delete, data: { confirm: "You sure?" } do %>
        <i class="fas fa-trash hover-red"></i>
      <% end %>
    <% end %>
  </div>

  <div class="border-bottom border-top">
    <div class="container">
      <%= render 'likes/like_posts', object: object%>
    </div>
  </div>

  <div class="pl-5 py-2">
      <div class=""><%= render 'comments/comment', object: object %></div>
      <div class="col-10 mt-3">
        <%= render 'comments/form', object: object %>
      </div>
  </div>
</div>
<br>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1> Timeline - My posts and my friends posts</h1>
<div class="center font-raleway ">
  <%= link_to new_post_path, class: "btn btn-secondary" do%>
    New Post?
  <%end%>
</div>

<% @all_posts.each do |p|%>
  <%= render 'posts/post_layout', object: p %>
<% end %>

app/views/posts/new.html.erb
<div class="col-md-6 mx-auto">
  <h1 class="center bold">Whats on your mind?</h1>
  <p>Create a new post for your friends to spy on</p>

  <%= form_for(@post) do |f| %>
      <%= render "devise/shared/error_messages", resource: @post %>
      <div class="form-group">
        <%= f.text_area :content, class:"form-control" %><br />
      </div>
      <div>
        <%= f.submit 'New Post', class:"btn btn-secondary col-md-3"%>
      </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<h1>Post</h1>
<%= render 'posts/post_layout', object: @post %>