config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  devise_for :users
  resources :users, only: %i[index show] do
    resources :friendships, only: %i[create] do
      collection do
        get 'accept_friend'
        get 'decline_friend'
      end
    end
  end
  
  put '/users/:id', to:  'users#update_img'

  resources :posts, only: %i[index new create show destroy] do
      resources :likes, only: %i[create]
  end
  resources :comments, only: %i[new create destroy] do
    resources :likes, only: %i[create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-primary">
    <div class= "container-fluid mx-auto"> 
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-flex">
                    <li class="nav-item"> <%= link_to 'Home', posts_path, class: "text-light nav-link"%> </li>

                    <li class="nav-item">
                    <%= link_to 'Find Friends', users_path, class: "text-light nav-link"%></li>
                    <% if user_signed_in? %>
                    <li class="nav-item">
                         <a class="nav-link text-white"  href="#"><%= current_user.notifications.count%>notifications</a>
                    </li>
                    
                </ul>

                <div class="float-right">
                 <%= link_to "Profile", user_path(current_user), class: "text-white mr-3"%> 
                    <%= link_to "Logout", destroy_user_session_path, class: "text-white", method: :delete %></li>
                    <% else %>
                    <%= link_to 'Login or SignUp', new_user_session_path, class:'text-white'%>
                </div>
                <% end %>
    </div>
           
</nav>
        
        <% if user_signed_in? %>
        
        <%end%>
     

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'layouts/header'%>
    <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    </div>
    <%= yield %>
  </body>
</html>